package com.orchard.ehow.dao;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;

public class EnrollProjectExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table enroll_project
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table enroll_project
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table enroll_project
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enroll_project
     *
     * @mbg.generated
     */
    public EnrollProjectExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enroll_project
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enroll_project
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enroll_project
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enroll_project
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enroll_project
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enroll_project
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enroll_project
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enroll_project
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public EnrollProjectExample orderBy(String orderByClause) {
        this.setOrderByClause(orderByClause);
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enroll_project
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public EnrollProjectExample orderBy(String ... orderByClauses) {
        StringBuffer sb = new StringBuffer();
        for (int i = 0; i < orderByClauses.length; i++) {
            sb.append(orderByClauses[i]);
            if (i < orderByClauses.length - 1) {
                sb.append(" , ");
            }
        }
        this.setOrderByClause(sb.toString());
        return this;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enroll_project
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enroll_project
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria(this);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enroll_project
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enroll_project
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public static Criteria newAndCreateCriteria() {
        EnrollProjectExample example = new EnrollProjectExample();
        return example.createCriteria();
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table enroll_project
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andProjectNameIsNull() {
            addCriterion("project_name is null");
            return (Criteria) this;
        }

        public Criteria andProjectNameIsNotNull() {
            addCriterion("project_name is not null");
            return (Criteria) this;
        }

        public Criteria andProjectNameEqualTo(String value) {
            addCriterion("project_name =", value, "projectName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_project
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andProjectNameEqualToColumn(EnrollProject.Column column) {
            addCriterion(new StringBuilder("project_name = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andProjectNameNotEqualTo(String value) {
            addCriterion("project_name <>", value, "projectName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_project
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andProjectNameNotEqualToColumn(EnrollProject.Column column) {
            addCriterion(new StringBuilder("project_name <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andProjectNameGreaterThan(String value) {
            addCriterion("project_name >", value, "projectName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_project
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andProjectNameGreaterThanColumn(EnrollProject.Column column) {
            addCriterion(new StringBuilder("project_name > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andProjectNameGreaterThanOrEqualTo(String value) {
            addCriterion("project_name >=", value, "projectName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_project
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andProjectNameGreaterThanOrEqualToColumn(EnrollProject.Column column) {
            addCriterion(new StringBuilder("project_name >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andProjectNameLessThan(String value) {
            addCriterion("project_name <", value, "projectName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_project
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andProjectNameLessThanColumn(EnrollProject.Column column) {
            addCriterion(new StringBuilder("project_name < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andProjectNameLessThanOrEqualTo(String value) {
            addCriterion("project_name <=", value, "projectName");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_project
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andProjectNameLessThanOrEqualToColumn(EnrollProject.Column column) {
            addCriterion(new StringBuilder("project_name <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andProjectNameLike(String value) {
            addCriterion("project_name like", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameNotLike(String value) {
            addCriterion("project_name not like", value, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameIn(List<String> values) {
            addCriterion("project_name in", values, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameNotIn(List<String> values) {
            addCriterion("project_name not in", values, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameBetween(String value1, String value2) {
            addCriterion("project_name between", value1, value2, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectNameNotBetween(String value1, String value2) {
            addCriterion("project_name not between", value1, value2, "projectName");
            return (Criteria) this;
        }

        public Criteria andProjectCodeIsNull() {
            addCriterion("project_code is null");
            return (Criteria) this;
        }

        public Criteria andProjectCodeIsNotNull() {
            addCriterion("project_code is not null");
            return (Criteria) this;
        }

        public Criteria andProjectCodeEqualTo(String value) {
            addCriterion("project_code =", value, "projectCode");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_project
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andProjectCodeEqualToColumn(EnrollProject.Column column) {
            addCriterion(new StringBuilder("project_code = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andProjectCodeNotEqualTo(String value) {
            addCriterion("project_code <>", value, "projectCode");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_project
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andProjectCodeNotEqualToColumn(EnrollProject.Column column) {
            addCriterion(new StringBuilder("project_code <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andProjectCodeGreaterThan(String value) {
            addCriterion("project_code >", value, "projectCode");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_project
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andProjectCodeGreaterThanColumn(EnrollProject.Column column) {
            addCriterion(new StringBuilder("project_code > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andProjectCodeGreaterThanOrEqualTo(String value) {
            addCriterion("project_code >=", value, "projectCode");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_project
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andProjectCodeGreaterThanOrEqualToColumn(EnrollProject.Column column) {
            addCriterion(new StringBuilder("project_code >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andProjectCodeLessThan(String value) {
            addCriterion("project_code <", value, "projectCode");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_project
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andProjectCodeLessThanColumn(EnrollProject.Column column) {
            addCriterion(new StringBuilder("project_code < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andProjectCodeLessThanOrEqualTo(String value) {
            addCriterion("project_code <=", value, "projectCode");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_project
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andProjectCodeLessThanOrEqualToColumn(EnrollProject.Column column) {
            addCriterion(new StringBuilder("project_code <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andProjectCodeLike(String value) {
            addCriterion("project_code like", value, "projectCode");
            return (Criteria) this;
        }

        public Criteria andProjectCodeNotLike(String value) {
            addCriterion("project_code not like", value, "projectCode");
            return (Criteria) this;
        }

        public Criteria andProjectCodeIn(List<String> values) {
            addCriterion("project_code in", values, "projectCode");
            return (Criteria) this;
        }

        public Criteria andProjectCodeNotIn(List<String> values) {
            addCriterion("project_code not in", values, "projectCode");
            return (Criteria) this;
        }

        public Criteria andProjectCodeBetween(String value1, String value2) {
            addCriterion("project_code between", value1, value2, "projectCode");
            return (Criteria) this;
        }

        public Criteria andProjectCodeNotBetween(String value1, String value2) {
            addCriterion("project_code not between", value1, value2, "projectCode");
            return (Criteria) this;
        }

        public Criteria andOngoingIsNull() {
            addCriterion("ongoing is null");
            return (Criteria) this;
        }

        public Criteria andOngoingIsNotNull() {
            addCriterion("ongoing is not null");
            return (Criteria) this;
        }

        public Criteria andOngoingEqualTo(Integer value) {
            addCriterion("ongoing =", value, "ongoing");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_project
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andOngoingEqualToColumn(EnrollProject.Column column) {
            addCriterion(new StringBuilder("ongoing = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andOngoingNotEqualTo(Integer value) {
            addCriterion("ongoing <>", value, "ongoing");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_project
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andOngoingNotEqualToColumn(EnrollProject.Column column) {
            addCriterion(new StringBuilder("ongoing <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andOngoingGreaterThan(Integer value) {
            addCriterion("ongoing >", value, "ongoing");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_project
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andOngoingGreaterThanColumn(EnrollProject.Column column) {
            addCriterion(new StringBuilder("ongoing > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andOngoingGreaterThanOrEqualTo(Integer value) {
            addCriterion("ongoing >=", value, "ongoing");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_project
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andOngoingGreaterThanOrEqualToColumn(EnrollProject.Column column) {
            addCriterion(new StringBuilder("ongoing >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andOngoingLessThan(Integer value) {
            addCriterion("ongoing <", value, "ongoing");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_project
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andOngoingLessThanColumn(EnrollProject.Column column) {
            addCriterion(new StringBuilder("ongoing < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andOngoingLessThanOrEqualTo(Integer value) {
            addCriterion("ongoing <=", value, "ongoing");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_project
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andOngoingLessThanOrEqualToColumn(EnrollProject.Column column) {
            addCriterion(new StringBuilder("ongoing <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andOngoingIn(List<Integer> values) {
            addCriterion("ongoing in", values, "ongoing");
            return (Criteria) this;
        }

        public Criteria andOngoingNotIn(List<Integer> values) {
            addCriterion("ongoing not in", values, "ongoing");
            return (Criteria) this;
        }

        public Criteria andOngoingBetween(Integer value1, Integer value2) {
            addCriterion("ongoing between", value1, value2, "ongoing");
            return (Criteria) this;
        }

        public Criteria andOngoingNotBetween(Integer value1, Integer value2) {
            addCriterion("ongoing not between", value1, value2, "ongoing");
            return (Criteria) this;
        }

        public Criteria andExpireDateIsNull() {
            addCriterion("expire_date is null");
            return (Criteria) this;
        }

        public Criteria andExpireDateIsNotNull() {
            addCriterion("expire_date is not null");
            return (Criteria) this;
        }

        public Criteria andExpireDateEqualTo(LocalDateTime value) {
            addCriterion("expire_date =", value, "expireDate");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_project
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andExpireDateEqualToColumn(EnrollProject.Column column) {
            addCriterion(new StringBuilder("expire_date = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andExpireDateNotEqualTo(LocalDateTime value) {
            addCriterion("expire_date <>", value, "expireDate");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_project
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andExpireDateNotEqualToColumn(EnrollProject.Column column) {
            addCriterion(new StringBuilder("expire_date <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andExpireDateGreaterThan(LocalDateTime value) {
            addCriterion("expire_date >", value, "expireDate");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_project
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andExpireDateGreaterThanColumn(EnrollProject.Column column) {
            addCriterion(new StringBuilder("expire_date > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andExpireDateGreaterThanOrEqualTo(LocalDateTime value) {
            addCriterion("expire_date >=", value, "expireDate");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_project
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andExpireDateGreaterThanOrEqualToColumn(EnrollProject.Column column) {
            addCriterion(new StringBuilder("expire_date >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andExpireDateLessThan(LocalDateTime value) {
            addCriterion("expire_date <", value, "expireDate");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_project
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andExpireDateLessThanColumn(EnrollProject.Column column) {
            addCriterion(new StringBuilder("expire_date < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andExpireDateLessThanOrEqualTo(LocalDateTime value) {
            addCriterion("expire_date <=", value, "expireDate");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_project
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andExpireDateLessThanOrEqualToColumn(EnrollProject.Column column) {
            addCriterion(new StringBuilder("expire_date <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andExpireDateIn(List<LocalDateTime> values) {
            addCriterion("expire_date in", values, "expireDate");
            return (Criteria) this;
        }

        public Criteria andExpireDateNotIn(List<LocalDateTime> values) {
            addCriterion("expire_date not in", values, "expireDate");
            return (Criteria) this;
        }

        public Criteria andExpireDateBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("expire_date between", value1, value2, "expireDate");
            return (Criteria) this;
        }

        public Criteria andExpireDateNotBetween(LocalDateTime value1, LocalDateTime value2) {
            addCriterion("expire_date not between", value1, value2, "expireDate");
            return (Criteria) this;
        }

        public Criteria andAllowUnionIsNull() {
            addCriterion("allow_union is null");
            return (Criteria) this;
        }

        public Criteria andAllowUnionIsNotNull() {
            addCriterion("allow_union is not null");
            return (Criteria) this;
        }

        public Criteria andAllowUnionEqualTo(String value) {
            addCriterion("allow_union =", value, "allowUnion");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_project
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andAllowUnionEqualToColumn(EnrollProject.Column column) {
            addCriterion(new StringBuilder("allow_union = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andAllowUnionNotEqualTo(String value) {
            addCriterion("allow_union <>", value, "allowUnion");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_project
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andAllowUnionNotEqualToColumn(EnrollProject.Column column) {
            addCriterion(new StringBuilder("allow_union <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andAllowUnionGreaterThan(String value) {
            addCriterion("allow_union >", value, "allowUnion");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_project
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andAllowUnionGreaterThanColumn(EnrollProject.Column column) {
            addCriterion(new StringBuilder("allow_union > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andAllowUnionGreaterThanOrEqualTo(String value) {
            addCriterion("allow_union >=", value, "allowUnion");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_project
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andAllowUnionGreaterThanOrEqualToColumn(EnrollProject.Column column) {
            addCriterion(new StringBuilder("allow_union >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andAllowUnionLessThan(String value) {
            addCriterion("allow_union <", value, "allowUnion");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_project
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andAllowUnionLessThanColumn(EnrollProject.Column column) {
            addCriterion(new StringBuilder("allow_union < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andAllowUnionLessThanOrEqualTo(String value) {
            addCriterion("allow_union <=", value, "allowUnion");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_project
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andAllowUnionLessThanOrEqualToColumn(EnrollProject.Column column) {
            addCriterion(new StringBuilder("allow_union <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andAllowUnionLike(String value) {
            addCriterion("allow_union like", value, "allowUnion");
            return (Criteria) this;
        }

        public Criteria andAllowUnionNotLike(String value) {
            addCriterion("allow_union not like", value, "allowUnion");
            return (Criteria) this;
        }

        public Criteria andAllowUnionIn(List<String> values) {
            addCriterion("allow_union in", values, "allowUnion");
            return (Criteria) this;
        }

        public Criteria andAllowUnionNotIn(List<String> values) {
            addCriterion("allow_union not in", values, "allowUnion");
            return (Criteria) this;
        }

        public Criteria andAllowUnionBetween(String value1, String value2) {
            addCriterion("allow_union between", value1, value2, "allowUnion");
            return (Criteria) this;
        }

        public Criteria andAllowUnionNotBetween(String value1, String value2) {
            addCriterion("allow_union not between", value1, value2, "allowUnion");
            return (Criteria) this;
        }

        public Criteria andMaxUnionNumbersIsNull() {
            addCriterion("max_union_numbers is null");
            return (Criteria) this;
        }

        public Criteria andMaxUnionNumbersIsNotNull() {
            addCriterion("max_union_numbers is not null");
            return (Criteria) this;
        }

        public Criteria andMaxUnionNumbersEqualTo(Integer value) {
            addCriterion("max_union_numbers =", value, "maxUnionNumbers");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_project
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andMaxUnionNumbersEqualToColumn(EnrollProject.Column column) {
            addCriterion(new StringBuilder("max_union_numbers = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMaxUnionNumbersNotEqualTo(Integer value) {
            addCriterion("max_union_numbers <>", value, "maxUnionNumbers");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_project
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andMaxUnionNumbersNotEqualToColumn(EnrollProject.Column column) {
            addCriterion(new StringBuilder("max_union_numbers <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMaxUnionNumbersGreaterThan(Integer value) {
            addCriterion("max_union_numbers >", value, "maxUnionNumbers");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_project
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andMaxUnionNumbersGreaterThanColumn(EnrollProject.Column column) {
            addCriterion(new StringBuilder("max_union_numbers > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMaxUnionNumbersGreaterThanOrEqualTo(Integer value) {
            addCriterion("max_union_numbers >=", value, "maxUnionNumbers");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_project
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andMaxUnionNumbersGreaterThanOrEqualToColumn(EnrollProject.Column column) {
            addCriterion(new StringBuilder("max_union_numbers >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMaxUnionNumbersLessThan(Integer value) {
            addCriterion("max_union_numbers <", value, "maxUnionNumbers");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_project
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andMaxUnionNumbersLessThanColumn(EnrollProject.Column column) {
            addCriterion(new StringBuilder("max_union_numbers < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMaxUnionNumbersLessThanOrEqualTo(Integer value) {
            addCriterion("max_union_numbers <=", value, "maxUnionNumbers");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_project
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andMaxUnionNumbersLessThanOrEqualToColumn(EnrollProject.Column column) {
            addCriterion(new StringBuilder("max_union_numbers <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMaxUnionNumbersIn(List<Integer> values) {
            addCriterion("max_union_numbers in", values, "maxUnionNumbers");
            return (Criteria) this;
        }

        public Criteria andMaxUnionNumbersNotIn(List<Integer> values) {
            addCriterion("max_union_numbers not in", values, "maxUnionNumbers");
            return (Criteria) this;
        }

        public Criteria andMaxUnionNumbersBetween(Integer value1, Integer value2) {
            addCriterion("max_union_numbers between", value1, value2, "maxUnionNumbers");
            return (Criteria) this;
        }

        public Criteria andMaxUnionNumbersNotBetween(Integer value1, Integer value2) {
            addCriterion("max_union_numbers not between", value1, value2, "maxUnionNumbers");
            return (Criteria) this;
        }

        public Criteria andCompanyAchieveNumbersIsNull() {
            addCriterion("company_achieve_numbers is null");
            return (Criteria) this;
        }

        public Criteria andCompanyAchieveNumbersIsNotNull() {
            addCriterion("company_achieve_numbers is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyAchieveNumbersEqualTo(Integer value) {
            addCriterion("company_achieve_numbers =", value, "companyAchieveNumbers");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_project
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCompanyAchieveNumbersEqualToColumn(EnrollProject.Column column) {
            addCriterion(new StringBuilder("company_achieve_numbers = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCompanyAchieveNumbersNotEqualTo(Integer value) {
            addCriterion("company_achieve_numbers <>", value, "companyAchieveNumbers");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_project
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCompanyAchieveNumbersNotEqualToColumn(EnrollProject.Column column) {
            addCriterion(new StringBuilder("company_achieve_numbers <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCompanyAchieveNumbersGreaterThan(Integer value) {
            addCriterion("company_achieve_numbers >", value, "companyAchieveNumbers");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_project
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCompanyAchieveNumbersGreaterThanColumn(EnrollProject.Column column) {
            addCriterion(new StringBuilder("company_achieve_numbers > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCompanyAchieveNumbersGreaterThanOrEqualTo(Integer value) {
            addCriterion("company_achieve_numbers >=", value, "companyAchieveNumbers");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_project
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCompanyAchieveNumbersGreaterThanOrEqualToColumn(EnrollProject.Column column) {
            addCriterion(new StringBuilder("company_achieve_numbers >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCompanyAchieveNumbersLessThan(Integer value) {
            addCriterion("company_achieve_numbers <", value, "companyAchieveNumbers");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_project
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCompanyAchieveNumbersLessThanColumn(EnrollProject.Column column) {
            addCriterion(new StringBuilder("company_achieve_numbers < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCompanyAchieveNumbersLessThanOrEqualTo(Integer value) {
            addCriterion("company_achieve_numbers <=", value, "companyAchieveNumbers");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_project
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andCompanyAchieveNumbersLessThanOrEqualToColumn(EnrollProject.Column column) {
            addCriterion(new StringBuilder("company_achieve_numbers <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andCompanyAchieveNumbersIn(List<Integer> values) {
            addCriterion("company_achieve_numbers in", values, "companyAchieveNumbers");
            return (Criteria) this;
        }

        public Criteria andCompanyAchieveNumbersNotIn(List<Integer> values) {
            addCriterion("company_achieve_numbers not in", values, "companyAchieveNumbers");
            return (Criteria) this;
        }

        public Criteria andCompanyAchieveNumbersBetween(Integer value1, Integer value2) {
            addCriterion("company_achieve_numbers between", value1, value2, "companyAchieveNumbers");
            return (Criteria) this;
        }

        public Criteria andCompanyAchieveNumbersNotBetween(Integer value1, Integer value2) {
            addCriterion("company_achieve_numbers not between", value1, value2, "companyAchieveNumbers");
            return (Criteria) this;
        }

        public Criteria andMemberAchieveNumbersIsNull() {
            addCriterion("member_achieve_numbers is null");
            return (Criteria) this;
        }

        public Criteria andMemberAchieveNumbersIsNotNull() {
            addCriterion("member_achieve_numbers is not null");
            return (Criteria) this;
        }

        public Criteria andMemberAchieveNumbersEqualTo(Integer value) {
            addCriterion("member_achieve_numbers =", value, "memberAchieveNumbers");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_project
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andMemberAchieveNumbersEqualToColumn(EnrollProject.Column column) {
            addCriterion(new StringBuilder("member_achieve_numbers = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMemberAchieveNumbersNotEqualTo(Integer value) {
            addCriterion("member_achieve_numbers <>", value, "memberAchieveNumbers");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_project
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andMemberAchieveNumbersNotEqualToColumn(EnrollProject.Column column) {
            addCriterion(new StringBuilder("member_achieve_numbers <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMemberAchieveNumbersGreaterThan(Integer value) {
            addCriterion("member_achieve_numbers >", value, "memberAchieveNumbers");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_project
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andMemberAchieveNumbersGreaterThanColumn(EnrollProject.Column column) {
            addCriterion(new StringBuilder("member_achieve_numbers > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMemberAchieveNumbersGreaterThanOrEqualTo(Integer value) {
            addCriterion("member_achieve_numbers >=", value, "memberAchieveNumbers");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_project
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andMemberAchieveNumbersGreaterThanOrEqualToColumn(EnrollProject.Column column) {
            addCriterion(new StringBuilder("member_achieve_numbers >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMemberAchieveNumbersLessThan(Integer value) {
            addCriterion("member_achieve_numbers <", value, "memberAchieveNumbers");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_project
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andMemberAchieveNumbersLessThanColumn(EnrollProject.Column column) {
            addCriterion(new StringBuilder("member_achieve_numbers < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMemberAchieveNumbersLessThanOrEqualTo(Integer value) {
            addCriterion("member_achieve_numbers <=", value, "memberAchieveNumbers");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_project
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andMemberAchieveNumbersLessThanOrEqualToColumn(EnrollProject.Column column) {
            addCriterion(new StringBuilder("member_achieve_numbers <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andMemberAchieveNumbersIn(List<Integer> values) {
            addCriterion("member_achieve_numbers in", values, "memberAchieveNumbers");
            return (Criteria) this;
        }

        public Criteria andMemberAchieveNumbersNotIn(List<Integer> values) {
            addCriterion("member_achieve_numbers not in", values, "memberAchieveNumbers");
            return (Criteria) this;
        }

        public Criteria andMemberAchieveNumbersBetween(Integer value1, Integer value2) {
            addCriterion("member_achieve_numbers between", value1, value2, "memberAchieveNumbers");
            return (Criteria) this;
        }

        public Criteria andMemberAchieveNumbersNotBetween(Integer value1, Integer value2) {
            addCriterion("member_achieve_numbers not between", value1, value2, "memberAchieveNumbers");
            return (Criteria) this;
        }

        public Criteria andTipsIsNull() {
            addCriterion("tips is null");
            return (Criteria) this;
        }

        public Criteria andTipsIsNotNull() {
            addCriterion("tips is not null");
            return (Criteria) this;
        }

        public Criteria andTipsEqualTo(String value) {
            addCriterion("tips =", value, "tips");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_project
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTipsEqualToColumn(EnrollProject.Column column) {
            addCriterion(new StringBuilder("tips = ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTipsNotEqualTo(String value) {
            addCriterion("tips <>", value, "tips");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_project
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTipsNotEqualToColumn(EnrollProject.Column column) {
            addCriterion(new StringBuilder("tips <> ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTipsGreaterThan(String value) {
            addCriterion("tips >", value, "tips");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_project
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTipsGreaterThanColumn(EnrollProject.Column column) {
            addCriterion(new StringBuilder("tips > ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTipsGreaterThanOrEqualTo(String value) {
            addCriterion("tips >=", value, "tips");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_project
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTipsGreaterThanOrEqualToColumn(EnrollProject.Column column) {
            addCriterion(new StringBuilder("tips >= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTipsLessThan(String value) {
            addCriterion("tips <", value, "tips");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_project
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTipsLessThanColumn(EnrollProject.Column column) {
            addCriterion(new StringBuilder("tips < ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTipsLessThanOrEqualTo(String value) {
            addCriterion("tips <=", value, "tips");
            return (Criteria) this;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_project
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andTipsLessThanOrEqualToColumn(EnrollProject.Column column) {
            addCriterion(new StringBuilder("tips <= ").append(column.getEscapedColumnName()).toString());
            return (Criteria) this;
        }

        public Criteria andTipsLike(String value) {
            addCriterion("tips like", value, "tips");
            return (Criteria) this;
        }

        public Criteria andTipsNotLike(String value) {
            addCriterion("tips not like", value, "tips");
            return (Criteria) this;
        }

        public Criteria andTipsIn(List<String> values) {
            addCriterion("tips in", values, "tips");
            return (Criteria) this;
        }

        public Criteria andTipsNotIn(List<String> values) {
            addCriterion("tips not in", values, "tips");
            return (Criteria) this;
        }

        public Criteria andTipsBetween(String value1, String value2) {
            addCriterion("tips between", value1, value2, "tips");
            return (Criteria) this;
        }

        public Criteria andTipsNotBetween(String value1, String value2) {
            addCriterion("tips not between", value1, value2, "tips");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table enroll_project
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {
        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table enroll_project
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private EnrollProjectExample example;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_project
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        protected Criteria(EnrollProjectExample example) {
            super();
            this.example = example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_project
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public EnrollProjectExample example() {
            return this.example;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_project
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public Criteria andIf(boolean ifAdd, ICriteriaAdd add) {
            if (ifAdd) {
                add.add(this);
            }
            return this;
        }

        /**
         * This interface was generated by MyBatis Generator.
         * This interface corresponds to the database table enroll_project
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public interface ICriteriaAdd {
            /**
             * This method was generated by MyBatis Generator.
             * This method corresponds to the database table enroll_project
             *
             * @mbg.generated
             * @project https://github.com/itfsw/mybatis-generator-plugin
             */
            Criteria add(Criteria add);
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table enroll_project
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}