package com.orchard.ehow.dao;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class EnrollEnrollsinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enroll_enrollsinfo.project_name
     *
     * @mbg.generated
     */
    private String projectName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enroll_enrollsinfo.project_code
     *
     * @mbg.generated
     */
    private String projectCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enroll_enrollsinfo.region_name
     *
     * @mbg.generated
     */
    private String regionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enroll_enrollsinfo.company_achievement
     *
     * @mbg.generated
     */
    private String companyAchievement;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enroll_enrollsinfo.team_member
     *
     * @mbg.generated
     */
    private String teamMember;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enroll_enrollsinfo.phone_number
     *
     * @mbg.generated
     */
    private String phoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enroll_enrollsinfo.expire_date
     *
     * @mbg.generated
     */
    private LocalDateTime expireDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enroll_enrollsinfo.enroll_date
     *
     * @mbg.generated
     */
    private LocalDateTime enrollDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enroll_enrollsinfo.company_name
     *
     * @mbg.generated
     */
    private String companyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enroll_enrollsinfo.email_address
     *
     * @mbg.generated
     */
    private String emailAddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enroll_enrollsinfo.project_name
     *
     * @return the value of enroll_enrollsinfo.project_name
     *
     * @mbg.generated
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enroll_enrollsinfo.project_name
     *
     * @param projectName the value for enroll_enrollsinfo.project_name
     *
     * @mbg.generated
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enroll_enrollsinfo.project_code
     *
     * @return the value of enroll_enrollsinfo.project_code
     *
     * @mbg.generated
     */
    public String getProjectCode() {
        return projectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enroll_enrollsinfo.project_code
     *
     * @param projectCode the value for enroll_enrollsinfo.project_code
     *
     * @mbg.generated
     */
    public void setProjectCode(String projectCode) {
        this.projectCode = projectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enroll_enrollsinfo.region_name
     *
     * @return the value of enroll_enrollsinfo.region_name
     *
     * @mbg.generated
     */
    public String getRegionName() {
        return regionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enroll_enrollsinfo.region_name
     *
     * @param regionName the value for enroll_enrollsinfo.region_name
     *
     * @mbg.generated
     */
    public void setRegionName(String regionName) {
        this.regionName = regionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enroll_enrollsinfo.company_achievement
     *
     * @return the value of enroll_enrollsinfo.company_achievement
     *
     * @mbg.generated
     */
    public String getCompanyAchievement() {
        return companyAchievement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enroll_enrollsinfo.company_achievement
     *
     * @param companyAchievement the value for enroll_enrollsinfo.company_achievement
     *
     * @mbg.generated
     */
    public void setCompanyAchievement(String companyAchievement) {
        this.companyAchievement = companyAchievement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enroll_enrollsinfo.team_member
     *
     * @return the value of enroll_enrollsinfo.team_member
     *
     * @mbg.generated
     */
    public String getTeamMember() {
        return teamMember;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enroll_enrollsinfo.team_member
     *
     * @param teamMember the value for enroll_enrollsinfo.team_member
     *
     * @mbg.generated
     */
    public void setTeamMember(String teamMember) {
        this.teamMember = teamMember;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enroll_enrollsinfo.phone_number
     *
     * @return the value of enroll_enrollsinfo.phone_number
     *
     * @mbg.generated
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enroll_enrollsinfo.phone_number
     *
     * @param phoneNumber the value for enroll_enrollsinfo.phone_number
     *
     * @mbg.generated
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enroll_enrollsinfo.expire_date
     *
     * @return the value of enroll_enrollsinfo.expire_date
     *
     * @mbg.generated
     */
    public LocalDateTime getExpireDate() {
        return expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enroll_enrollsinfo.expire_date
     *
     * @param expireDate the value for enroll_enrollsinfo.expire_date
     *
     * @mbg.generated
     */
    public void setExpireDate(LocalDateTime expireDate) {
        this.expireDate = expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enroll_enrollsinfo.enroll_date
     *
     * @return the value of enroll_enrollsinfo.enroll_date
     *
     * @mbg.generated
     */
    public LocalDateTime getEnrollDate() {
        return enrollDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enroll_enrollsinfo.enroll_date
     *
     * @param enrollDate the value for enroll_enrollsinfo.enroll_date
     *
     * @mbg.generated
     */
    public void setEnrollDate(LocalDateTime enrollDate) {
        this.enrollDate = enrollDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enroll_enrollsinfo.company_name
     *
     * @return the value of enroll_enrollsinfo.company_name
     *
     * @mbg.generated
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enroll_enrollsinfo.company_name
     *
     * @param companyName the value for enroll_enrollsinfo.company_name
     *
     * @mbg.generated
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enroll_enrollsinfo.email_address
     *
     * @return the value of enroll_enrollsinfo.email_address
     *
     * @mbg.generated
     */
    public String getEmailAddress() {
        return emailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enroll_enrollsinfo.email_address
     *
     * @param emailAddress the value for enroll_enrollsinfo.email_address
     *
     * @mbg.generated
     */
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enroll_enrollsinfo
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", projectName=").append(projectName);
        sb.append(", projectCode=").append(projectCode);
        sb.append(", regionName=").append(regionName);
        sb.append(", companyAchievement=").append(companyAchievement);
        sb.append(", teamMember=").append(teamMember);
        sb.append(", phoneNumber=").append(phoneNumber);
        sb.append(", expireDate=").append(expireDate);
        sb.append(", enrollDate=").append(enrollDate);
        sb.append(", companyName=").append(companyName);
        sb.append(", emailAddress=").append(emailAddress);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enroll_enrollsinfo
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        EnrollEnrollsinfo other = (EnrollEnrollsinfo) that;
        return (this.getProjectName() == null ? other.getProjectName() == null : this.getProjectName().equals(other.getProjectName()))
            && (this.getProjectCode() == null ? other.getProjectCode() == null : this.getProjectCode().equals(other.getProjectCode()))
            && (this.getRegionName() == null ? other.getRegionName() == null : this.getRegionName().equals(other.getRegionName()))
            && (this.getCompanyAchievement() == null ? other.getCompanyAchievement() == null : this.getCompanyAchievement().equals(other.getCompanyAchievement()))
            && (this.getTeamMember() == null ? other.getTeamMember() == null : this.getTeamMember().equals(other.getTeamMember()))
            && (this.getPhoneNumber() == null ? other.getPhoneNumber() == null : this.getPhoneNumber().equals(other.getPhoneNumber()))
            && (this.getExpireDate() == null ? other.getExpireDate() == null : this.getExpireDate().equals(other.getExpireDate()))
            && (this.getEnrollDate() == null ? other.getEnrollDate() == null : this.getEnrollDate().equals(other.getEnrollDate()))
            && (this.getCompanyName() == null ? other.getCompanyName() == null : this.getCompanyName().equals(other.getCompanyName()))
            && (this.getEmailAddress() == null ? other.getEmailAddress() == null : this.getEmailAddress().equals(other.getEmailAddress()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enroll_enrollsinfo
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getProjectName() == null) ? 0 : getProjectName().hashCode());
        result = prime * result + ((getProjectCode() == null) ? 0 : getProjectCode().hashCode());
        result = prime * result + ((getRegionName() == null) ? 0 : getRegionName().hashCode());
        result = prime * result + ((getCompanyAchievement() == null) ? 0 : getCompanyAchievement().hashCode());
        result = prime * result + ((getTeamMember() == null) ? 0 : getTeamMember().hashCode());
        result = prime * result + ((getPhoneNumber() == null) ? 0 : getPhoneNumber().hashCode());
        result = prime * result + ((getExpireDate() == null) ? 0 : getExpireDate().hashCode());
        result = prime * result + ((getEnrollDate() == null) ? 0 : getEnrollDate().hashCode());
        result = prime * result + ((getCompanyName() == null) ? 0 : getCompanyName().hashCode());
        result = prime * result + ((getEmailAddress() == null) ? 0 : getEmailAddress().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table enroll_enrollsinfo
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        projectName("project_name", "projectName", "VARCHAR", false),
        projectCode("project_code", "projectCode", "VARCHAR", false),
        regionName("region_name", "regionName", "VARCHAR", false),
        companyAchievement("company_achievement", "companyAchievement", "VARCHAR", false),
        teamMember("team_member", "teamMember", "VARCHAR", false),
        phoneNumber("phone_number", "phoneNumber", "VARCHAR", false),
        expireDate("expire_date", "expireDate", "TIMESTAMP", false),
        enrollDate("enroll_date", "enrollDate", "TIMESTAMP", false),
        companyName("company_name", "companyName", "VARCHAR", false),
        emailAddress("email_address", "emailAddress", "VARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table enroll_enrollsinfo
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table enroll_enrollsinfo
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table enroll_enrollsinfo
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table enroll_enrollsinfo
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table enroll_enrollsinfo
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table enroll_enrollsinfo
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_enrollsinfo
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_enrollsinfo
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_enrollsinfo
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_enrollsinfo
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_enrollsinfo
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_enrollsinfo
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_enrollsinfo
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_enrollsinfo
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_enrollsinfo
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }
    }
}