package com.orchard.ehow.dao;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.Arrays;

public class EnrollEnrollsinfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enroll_enrollsinfo.project_name
     *
     * @mbg.generated
     */
    private String projectName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enroll_enrollsinfo.project_code
     *
     * @mbg.generated
     */
    private String projectCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enroll_enrollsinfo.region_name
     *
     * @mbg.generated
     */
    private String regionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enroll_enrollsinfo.company_name
     *
     * @mbg.generated
     */
    private String companyName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enroll_enrollsinfo.company_achievement3
     *
     * @mbg.generated
     */
    private String companyAchievement3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enroll_enrollsinfo.company_achievement4
     *
     * @mbg.generated
     */
    private String companyAchievement4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enroll_enrollsinfo.company_achievement5
     *
     * @mbg.generated
     */
    private String companyAchievement5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enroll_enrollsinfo.company_achievement2
     *
     * @mbg.generated
     */
    private String companyAchievement2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enroll_enrollsinfo.company_achievement1
     *
     * @mbg.generated
     */
    private String companyAchievement1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enroll_enrollsinfo.email_address
     *
     * @mbg.generated
     */
    private String emailAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enroll_enrollsinfo.contact
     *
     * @mbg.generated
     */
    private String contact;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enroll_enrollsinfo.phone_number
     *
     * @mbg.generated
     */
    private String phoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enroll_enrollsinfo.team_member
     *
     * @mbg.generated
     */
    private String teamMember;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enroll_enrollsinfo.expire_date
     *
     * @mbg.generated
     */
    private LocalDateTime expireDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enroll_enrollsinfo.enroll_date
     *
     * @mbg.generated
     */
    private LocalDateTime enrollDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enroll_enrollsinfo.member_achievement1
     *
     * @mbg.generated
     */
    private String memberAchievement1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enroll_enrollsinfo.member_achievement2
     *
     * @mbg.generated
     */
    private String memberAchievement2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enroll_enrollsinfo.member_achievement3
     *
     * @mbg.generated
     */
    private String memberAchievement3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enroll_enrollsinfo.member_achievement4
     *
     * @mbg.generated
     */
    private String memberAchievement4;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enroll_enrollsinfo.member_achievement5
     *
     * @mbg.generated
     */
    private String memberAchievement5;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enroll_enrollsinfo.member_award
     *
     * @mbg.generated
     */
    private String memberAward;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enroll_enrollsinfo.userId
     *
     * @mbg.generated
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enroll_enrollsinfo.union_type_code
     *
     * @mbg.generated
     */
    private String unionTypeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enroll_enrollsinfo.LEADER_COMPANY_ID
     *
     * @mbg.generated
     */
    private String leaderCompanyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enroll_enrollsinfo.union_type_name
     *
     * @mbg.generated
     */
    private String unionTypeName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enroll_enrollsinfo.project_name
     *
     * @return the value of enroll_enrollsinfo.project_name
     *
     * @mbg.generated
     */
    public String getProjectName() {
        return projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enroll_enrollsinfo.project_name
     *
     * @param projectName the value for enroll_enrollsinfo.project_name
     *
     * @mbg.generated
     */
    public void setProjectName(String projectName) {
        this.projectName = projectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enroll_enrollsinfo.project_code
     *
     * @return the value of enroll_enrollsinfo.project_code
     *
     * @mbg.generated
     */
    public String getProjectCode() {
        return projectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enroll_enrollsinfo.project_code
     *
     * @param projectCode the value for enroll_enrollsinfo.project_code
     *
     * @mbg.generated
     */
    public void setProjectCode(String projectCode) {
        this.projectCode = projectCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enroll_enrollsinfo.region_name
     *
     * @return the value of enroll_enrollsinfo.region_name
     *
     * @mbg.generated
     */
    public String getRegionName() {
        return regionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enroll_enrollsinfo.region_name
     *
     * @param regionName the value for enroll_enrollsinfo.region_name
     *
     * @mbg.generated
     */
    public void setRegionName(String regionName) {
        this.regionName = regionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enroll_enrollsinfo.company_name
     *
     * @return the value of enroll_enrollsinfo.company_name
     *
     * @mbg.generated
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enroll_enrollsinfo.company_name
     *
     * @param companyName the value for enroll_enrollsinfo.company_name
     *
     * @mbg.generated
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enroll_enrollsinfo.company_achievement3
     *
     * @return the value of enroll_enrollsinfo.company_achievement3
     *
     * @mbg.generated
     */
    public String getCompanyAchievement3() {
        return companyAchievement3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enroll_enrollsinfo.company_achievement3
     *
     * @param companyAchievement3 the value for enroll_enrollsinfo.company_achievement3
     *
     * @mbg.generated
     */
    public void setCompanyAchievement3(String companyAchievement3) {
        this.companyAchievement3 = companyAchievement3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enroll_enrollsinfo.company_achievement4
     *
     * @return the value of enroll_enrollsinfo.company_achievement4
     *
     * @mbg.generated
     */
    public String getCompanyAchievement4() {
        return companyAchievement4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enroll_enrollsinfo.company_achievement4
     *
     * @param companyAchievement4 the value for enroll_enrollsinfo.company_achievement4
     *
     * @mbg.generated
     */
    public void setCompanyAchievement4(String companyAchievement4) {
        this.companyAchievement4 = companyAchievement4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enroll_enrollsinfo.company_achievement5
     *
     * @return the value of enroll_enrollsinfo.company_achievement5
     *
     * @mbg.generated
     */
    public String getCompanyAchievement5() {
        return companyAchievement5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enroll_enrollsinfo.company_achievement5
     *
     * @param companyAchievement5 the value for enroll_enrollsinfo.company_achievement5
     *
     * @mbg.generated
     */
    public void setCompanyAchievement5(String companyAchievement5) {
        this.companyAchievement5 = companyAchievement5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enroll_enrollsinfo.company_achievement2
     *
     * @return the value of enroll_enrollsinfo.company_achievement2
     *
     * @mbg.generated
     */
    public String getCompanyAchievement2() {
        return companyAchievement2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enroll_enrollsinfo.company_achievement2
     *
     * @param companyAchievement2 the value for enroll_enrollsinfo.company_achievement2
     *
     * @mbg.generated
     */
    public void setCompanyAchievement2(String companyAchievement2) {
        this.companyAchievement2 = companyAchievement2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enroll_enrollsinfo.company_achievement1
     *
     * @return the value of enroll_enrollsinfo.company_achievement1
     *
     * @mbg.generated
     */
    public String getCompanyAchievement1() {
        return companyAchievement1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enroll_enrollsinfo.company_achievement1
     *
     * @param companyAchievement1 the value for enroll_enrollsinfo.company_achievement1
     *
     * @mbg.generated
     */
    public void setCompanyAchievement1(String companyAchievement1) {
        this.companyAchievement1 = companyAchievement1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enroll_enrollsinfo.email_address
     *
     * @return the value of enroll_enrollsinfo.email_address
     *
     * @mbg.generated
     */
    public String getEmailAddress() {
        return emailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enroll_enrollsinfo.email_address
     *
     * @param emailAddress the value for enroll_enrollsinfo.email_address
     *
     * @mbg.generated
     */
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enroll_enrollsinfo.contact
     *
     * @return the value of enroll_enrollsinfo.contact
     *
     * @mbg.generated
     */
    public String getContact() {
        return contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enroll_enrollsinfo.contact
     *
     * @param contact the value for enroll_enrollsinfo.contact
     *
     * @mbg.generated
     */
    public void setContact(String contact) {
        this.contact = contact;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enroll_enrollsinfo.phone_number
     *
     * @return the value of enroll_enrollsinfo.phone_number
     *
     * @mbg.generated
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enroll_enrollsinfo.phone_number
     *
     * @param phoneNumber the value for enroll_enrollsinfo.phone_number
     *
     * @mbg.generated
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enroll_enrollsinfo.team_member
     *
     * @return the value of enroll_enrollsinfo.team_member
     *
     * @mbg.generated
     */
    public String getTeamMember() {
        return teamMember;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enroll_enrollsinfo.team_member
     *
     * @param teamMember the value for enroll_enrollsinfo.team_member
     *
     * @mbg.generated
     */
    public void setTeamMember(String teamMember) {
        this.teamMember = teamMember;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enroll_enrollsinfo.expire_date
     *
     * @return the value of enroll_enrollsinfo.expire_date
     *
     * @mbg.generated
     */
    public LocalDateTime getExpireDate() {
        return expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enroll_enrollsinfo.expire_date
     *
     * @param expireDate the value for enroll_enrollsinfo.expire_date
     *
     * @mbg.generated
     */
    public void setExpireDate(LocalDateTime expireDate) {
        this.expireDate = expireDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enroll_enrollsinfo.enroll_date
     *
     * @return the value of enroll_enrollsinfo.enroll_date
     *
     * @mbg.generated
     */
    public LocalDateTime getEnrollDate() {
        return enrollDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enroll_enrollsinfo.enroll_date
     *
     * @param enrollDate the value for enroll_enrollsinfo.enroll_date
     *
     * @mbg.generated
     */
    public void setEnrollDate(LocalDateTime enrollDate) {
        this.enrollDate = enrollDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enroll_enrollsinfo.member_achievement1
     *
     * @return the value of enroll_enrollsinfo.member_achievement1
     *
     * @mbg.generated
     */
    public String getMemberAchievement1() {
        return memberAchievement1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enroll_enrollsinfo.member_achievement1
     *
     * @param memberAchievement1 the value for enroll_enrollsinfo.member_achievement1
     *
     * @mbg.generated
     */
    public void setMemberAchievement1(String memberAchievement1) {
        this.memberAchievement1 = memberAchievement1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enroll_enrollsinfo.member_achievement2
     *
     * @return the value of enroll_enrollsinfo.member_achievement2
     *
     * @mbg.generated
     */
    public String getMemberAchievement2() {
        return memberAchievement2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enroll_enrollsinfo.member_achievement2
     *
     * @param memberAchievement2 the value for enroll_enrollsinfo.member_achievement2
     *
     * @mbg.generated
     */
    public void setMemberAchievement2(String memberAchievement2) {
        this.memberAchievement2 = memberAchievement2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enroll_enrollsinfo.member_achievement3
     *
     * @return the value of enroll_enrollsinfo.member_achievement3
     *
     * @mbg.generated
     */
    public String getMemberAchievement3() {
        return memberAchievement3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enroll_enrollsinfo.member_achievement3
     *
     * @param memberAchievement3 the value for enroll_enrollsinfo.member_achievement3
     *
     * @mbg.generated
     */
    public void setMemberAchievement3(String memberAchievement3) {
        this.memberAchievement3 = memberAchievement3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enroll_enrollsinfo.member_achievement4
     *
     * @return the value of enroll_enrollsinfo.member_achievement4
     *
     * @mbg.generated
     */
    public String getMemberAchievement4() {
        return memberAchievement4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enroll_enrollsinfo.member_achievement4
     *
     * @param memberAchievement4 the value for enroll_enrollsinfo.member_achievement4
     *
     * @mbg.generated
     */
    public void setMemberAchievement4(String memberAchievement4) {
        this.memberAchievement4 = memberAchievement4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enroll_enrollsinfo.member_achievement5
     *
     * @return the value of enroll_enrollsinfo.member_achievement5
     *
     * @mbg.generated
     */
    public String getMemberAchievement5() {
        return memberAchievement5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enroll_enrollsinfo.member_achievement5
     *
     * @param memberAchievement5 the value for enroll_enrollsinfo.member_achievement5
     *
     * @mbg.generated
     */
    public void setMemberAchievement5(String memberAchievement5) {
        this.memberAchievement5 = memberAchievement5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enroll_enrollsinfo.member_award
     *
     * @return the value of enroll_enrollsinfo.member_award
     *
     * @mbg.generated
     */
    public String getMemberAward() {
        return memberAward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enroll_enrollsinfo.member_award
     *
     * @param memberAward the value for enroll_enrollsinfo.member_award
     *
     * @mbg.generated
     */
    public void setMemberAward(String memberAward) {
        this.memberAward = memberAward;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enroll_enrollsinfo.userId
     *
     * @return the value of enroll_enrollsinfo.userId
     *
     * @mbg.generated
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enroll_enrollsinfo.userId
     *
     * @param userid the value for enroll_enrollsinfo.userId
     *
     * @mbg.generated
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enroll_enrollsinfo.union_type_code
     *
     * @return the value of enroll_enrollsinfo.union_type_code
     *
     * @mbg.generated
     */
    public String getUnionTypeCode() {
        return unionTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enroll_enrollsinfo.union_type_code
     *
     * @param unionTypeCode the value for enroll_enrollsinfo.union_type_code
     *
     * @mbg.generated
     */
    public void setUnionTypeCode(String unionTypeCode) {
        this.unionTypeCode = unionTypeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enroll_enrollsinfo.LEADER_COMPANY_ID
     *
     * @return the value of enroll_enrollsinfo.LEADER_COMPANY_ID
     *
     * @mbg.generated
     */
    public String getLeaderCompanyId() {
        return leaderCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enroll_enrollsinfo.LEADER_COMPANY_ID
     *
     * @param leaderCompanyId the value for enroll_enrollsinfo.LEADER_COMPANY_ID
     *
     * @mbg.generated
     */
    public void setLeaderCompanyId(String leaderCompanyId) {
        this.leaderCompanyId = leaderCompanyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enroll_enrollsinfo.union_type_name
     *
     * @return the value of enroll_enrollsinfo.union_type_name
     *
     * @mbg.generated
     */
    public String getUnionTypeName() {
        return unionTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enroll_enrollsinfo.union_type_name
     *
     * @param unionTypeName the value for enroll_enrollsinfo.union_type_name
     *
     * @mbg.generated
     */
    public void setUnionTypeName(String unionTypeName) {
        this.unionTypeName = unionTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enroll_enrollsinfo
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", projectName=").append(projectName);
        sb.append(", projectCode=").append(projectCode);
        sb.append(", regionName=").append(regionName);
        sb.append(", companyName=").append(companyName);
        sb.append(", companyAchievement3=").append(companyAchievement3);
        sb.append(", companyAchievement4=").append(companyAchievement4);
        sb.append(", companyAchievement5=").append(companyAchievement5);
        sb.append(", companyAchievement2=").append(companyAchievement2);
        sb.append(", companyAchievement1=").append(companyAchievement1);
        sb.append(", emailAddress=").append(emailAddress);
        sb.append(", contact=").append(contact);
        sb.append(", phoneNumber=").append(phoneNumber);
        sb.append(", teamMember=").append(teamMember);
        sb.append(", expireDate=").append(expireDate);
        sb.append(", enrollDate=").append(enrollDate);
        sb.append(", memberAchievement1=").append(memberAchievement1);
        sb.append(", memberAchievement2=").append(memberAchievement2);
        sb.append(", memberAchievement3=").append(memberAchievement3);
        sb.append(", memberAchievement4=").append(memberAchievement4);
        sb.append(", memberAchievement5=").append(memberAchievement5);
        sb.append(", memberAward=").append(memberAward);
        sb.append(", userid=").append(userid);
        sb.append(", unionTypeCode=").append(unionTypeCode);
        sb.append(", leaderCompanyId=").append(leaderCompanyId);
        sb.append(", unionTypeName=").append(unionTypeName);
        sb.append("]");
        return sb.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enroll_enrollsinfo
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        EnrollEnrollsinfo other = (EnrollEnrollsinfo) that;
        return (this.getProjectName() == null ? other.getProjectName() == null : this.getProjectName().equals(other.getProjectName()))
            && (this.getProjectCode() == null ? other.getProjectCode() == null : this.getProjectCode().equals(other.getProjectCode()))
            && (this.getRegionName() == null ? other.getRegionName() == null : this.getRegionName().equals(other.getRegionName()))
            && (this.getCompanyName() == null ? other.getCompanyName() == null : this.getCompanyName().equals(other.getCompanyName()))
            && (this.getCompanyAchievement3() == null ? other.getCompanyAchievement3() == null : this.getCompanyAchievement3().equals(other.getCompanyAchievement3()))
            && (this.getCompanyAchievement4() == null ? other.getCompanyAchievement4() == null : this.getCompanyAchievement4().equals(other.getCompanyAchievement4()))
            && (this.getCompanyAchievement5() == null ? other.getCompanyAchievement5() == null : this.getCompanyAchievement5().equals(other.getCompanyAchievement5()))
            && (this.getCompanyAchievement2() == null ? other.getCompanyAchievement2() == null : this.getCompanyAchievement2().equals(other.getCompanyAchievement2()))
            && (this.getCompanyAchievement1() == null ? other.getCompanyAchievement1() == null : this.getCompanyAchievement1().equals(other.getCompanyAchievement1()))
            && (this.getEmailAddress() == null ? other.getEmailAddress() == null : this.getEmailAddress().equals(other.getEmailAddress()))
            && (this.getContact() == null ? other.getContact() == null : this.getContact().equals(other.getContact()))
            && (this.getPhoneNumber() == null ? other.getPhoneNumber() == null : this.getPhoneNumber().equals(other.getPhoneNumber()))
            && (this.getTeamMember() == null ? other.getTeamMember() == null : this.getTeamMember().equals(other.getTeamMember()))
            && (this.getExpireDate() == null ? other.getExpireDate() == null : this.getExpireDate().equals(other.getExpireDate()))
            && (this.getEnrollDate() == null ? other.getEnrollDate() == null : this.getEnrollDate().equals(other.getEnrollDate()))
            && (this.getMemberAchievement1() == null ? other.getMemberAchievement1() == null : this.getMemberAchievement1().equals(other.getMemberAchievement1()))
            && (this.getMemberAchievement2() == null ? other.getMemberAchievement2() == null : this.getMemberAchievement2().equals(other.getMemberAchievement2()))
            && (this.getMemberAchievement3() == null ? other.getMemberAchievement3() == null : this.getMemberAchievement3().equals(other.getMemberAchievement3()))
            && (this.getMemberAchievement4() == null ? other.getMemberAchievement4() == null : this.getMemberAchievement4().equals(other.getMemberAchievement4()))
            && (this.getMemberAchievement5() == null ? other.getMemberAchievement5() == null : this.getMemberAchievement5().equals(other.getMemberAchievement5()))
            && (this.getMemberAward() == null ? other.getMemberAward() == null : this.getMemberAward().equals(other.getMemberAward()))
            && (this.getUserid() == null ? other.getUserid() == null : this.getUserid().equals(other.getUserid()))
            && (this.getUnionTypeCode() == null ? other.getUnionTypeCode() == null : this.getUnionTypeCode().equals(other.getUnionTypeCode()))
            && (this.getLeaderCompanyId() == null ? other.getLeaderCompanyId() == null : this.getLeaderCompanyId().equals(other.getLeaderCompanyId()))
            && (this.getUnionTypeName() == null ? other.getUnionTypeName() == null : this.getUnionTypeName().equals(other.getUnionTypeName()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enroll_enrollsinfo
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getProjectName() == null) ? 0 : getProjectName().hashCode());
        result = prime * result + ((getProjectCode() == null) ? 0 : getProjectCode().hashCode());
        result = prime * result + ((getRegionName() == null) ? 0 : getRegionName().hashCode());
        result = prime * result + ((getCompanyName() == null) ? 0 : getCompanyName().hashCode());
        result = prime * result + ((getCompanyAchievement3() == null) ? 0 : getCompanyAchievement3().hashCode());
        result = prime * result + ((getCompanyAchievement4() == null) ? 0 : getCompanyAchievement4().hashCode());
        result = prime * result + ((getCompanyAchievement5() == null) ? 0 : getCompanyAchievement5().hashCode());
        result = prime * result + ((getCompanyAchievement2() == null) ? 0 : getCompanyAchievement2().hashCode());
        result = prime * result + ((getCompanyAchievement1() == null) ? 0 : getCompanyAchievement1().hashCode());
        result = prime * result + ((getEmailAddress() == null) ? 0 : getEmailAddress().hashCode());
        result = prime * result + ((getContact() == null) ? 0 : getContact().hashCode());
        result = prime * result + ((getPhoneNumber() == null) ? 0 : getPhoneNumber().hashCode());
        result = prime * result + ((getTeamMember() == null) ? 0 : getTeamMember().hashCode());
        result = prime * result + ((getExpireDate() == null) ? 0 : getExpireDate().hashCode());
        result = prime * result + ((getEnrollDate() == null) ? 0 : getEnrollDate().hashCode());
        result = prime * result + ((getMemberAchievement1() == null) ? 0 : getMemberAchievement1().hashCode());
        result = prime * result + ((getMemberAchievement2() == null) ? 0 : getMemberAchievement2().hashCode());
        result = prime * result + ((getMemberAchievement3() == null) ? 0 : getMemberAchievement3().hashCode());
        result = prime * result + ((getMemberAchievement4() == null) ? 0 : getMemberAchievement4().hashCode());
        result = prime * result + ((getMemberAchievement5() == null) ? 0 : getMemberAchievement5().hashCode());
        result = prime * result + ((getMemberAward() == null) ? 0 : getMemberAward().hashCode());
        result = prime * result + ((getUserid() == null) ? 0 : getUserid().hashCode());
        result = prime * result + ((getUnionTypeCode() == null) ? 0 : getUnionTypeCode().hashCode());
        result = prime * result + ((getLeaderCompanyId() == null) ? 0 : getLeaderCompanyId().hashCode());
        result = prime * result + ((getUnionTypeName() == null) ? 0 : getUnionTypeName().hashCode());
        return result;
    }

    /**
     * This enum was generated by MyBatis Generator.
     * This enum corresponds to the database table enroll_enrollsinfo
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    public enum Column {
        projectName("project_name", "projectName", "VARCHAR", false),
        projectCode("project_code", "projectCode", "VARCHAR", false),
        regionName("region_name", "regionName", "VARCHAR", false),
        companyName("company_name", "companyName", "VARCHAR", false),
        companyAchievement3("company_achievement3", "companyAchievement3", "VARCHAR", false),
        companyAchievement4("company_achievement4", "companyAchievement4", "VARCHAR", false),
        companyAchievement5("company_achievement5", "companyAchievement5", "VARCHAR", false),
        companyAchievement2("company_achievement2", "companyAchievement2", "VARCHAR", false),
        companyAchievement1("company_achievement1", "companyAchievement1", "VARCHAR", false),
        emailAddress("email_address", "emailAddress", "VARCHAR", false),
        contact("contact", "contact", "VARCHAR", false),
        phoneNumber("phone_number", "phoneNumber", "VARCHAR", false),
        teamMember("team_member", "teamMember", "VARCHAR", false),
        expireDate("expire_date", "expireDate", "TIMESTAMP", false),
        enrollDate("enroll_date", "enrollDate", "TIMESTAMP", false),
        memberAchievement1("member_achievement1", "memberAchievement1", "VARCHAR", false),
        memberAchievement2("member_achievement2", "memberAchievement2", "VARCHAR", false),
        memberAchievement3("member_achievement3", "memberAchievement3", "VARCHAR", false),
        memberAchievement4("member_achievement4", "memberAchievement4", "VARCHAR", false),
        memberAchievement5("member_achievement5", "memberAchievement5", "VARCHAR", false),
        memberAward("member_award", "memberAward", "VARCHAR", false),
        userid("userId", "userid", "VARCHAR", false),
        unionTypeCode("union_type_code", "unionTypeCode", "VARCHAR", false),
        leaderCompanyId("LEADER_COMPANY_ID", "leaderCompanyId", "VARCHAR", false),
        unionTypeName("union_type_name", "unionTypeName", "VARCHAR", false);

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table enroll_enrollsinfo
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String BEGINNING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table enroll_enrollsinfo
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private static final String ENDING_DELIMITER = "`";

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table enroll_enrollsinfo
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String column;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table enroll_enrollsinfo
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final boolean isColumnNameDelimited;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table enroll_enrollsinfo
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String javaProperty;

        /**
         * This field was generated by MyBatis Generator.
         * This field corresponds to the database table enroll_enrollsinfo
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        private final String jdbcType;

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_enrollsinfo
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String value() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_enrollsinfo
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getValue() {
            return this.column;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_enrollsinfo
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJavaProperty() {
            return this.javaProperty;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_enrollsinfo
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getJdbcType() {
            return this.jdbcType;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_enrollsinfo
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        Column(String column, String javaProperty, String jdbcType, boolean isColumnNameDelimited) {
            this.column = column;
            this.javaProperty = javaProperty;
            this.jdbcType = jdbcType;
            this.isColumnNameDelimited = isColumnNameDelimited;
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_enrollsinfo
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String desc() {
            return this.getEscapedColumnName() + " DESC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_enrollsinfo
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String asc() {
            return this.getEscapedColumnName() + " ASC";
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_enrollsinfo
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public static Column[] excludes(Column ... excludes) {
            ArrayList<Column> columns = new ArrayList<>(Arrays.asList(Column.values()));
            if (excludes != null && excludes.length > 0) {
                columns.removeAll(new ArrayList<>(Arrays.asList(excludes)));
            }
            return columns.toArray(new Column[]{});
        }

        /**
         * This method was generated by MyBatis Generator.
         * This method corresponds to the database table enroll_enrollsinfo
         *
         * @mbg.generated
         * @project https://github.com/itfsw/mybatis-generator-plugin
         */
        public String getEscapedColumnName() {
            if (this.isColumnNameDelimited) {
                return new StringBuilder().append(BEGINNING_DELIMITER).append(this.column).append(ENDING_DELIMITER).toString();
            } else {
                return this.column;
            }
        }
    }
}